import React, { useState } from 'react';
import { UserPlus, Search, Shield, User as UserIcon, Trash2, Key } from 'lucide-react';
import { User, UserRole } from '../types';
import { cn } from '../lib/utils';

export const UserMgmtView = ({ users, onAddUser, onDeleteUser }: { 
  users: User[], 
  onAddUser: (user: User) => void,
  onDeleteUser: (id: string) => void
}) => {
  const [showAdd, setShowAdd] = useState(false);
  const [newUser, setNewUser] = useState({ username: '', name: '', password: '', role: 'staff' as UserRole });

  const handleAdd = () => {
    if (!newUser.username || !newUser.password || !newUser.name) return;
    onAddUser({
      id: '', // ID will be generated by Firebase
      ...newUser,
      storeId: '' // Will be filled by App.tsx
    });
    setNewUser({ username: '', name: '', password: '', role: 'staff' });
    setShowAdd(false);
  };

  return (
    <div className="p-8 space-y-6 h-full overflow-y-auto">
      <div className="flex justify-between items-center">
        <h3 className="text-xl font-bold text-white flex items-center gap-2">
          <Shield className="w-6 h-6 text-emerald-500" />
          Quản lý Nhân viên
        </h3>
        <button 
          onClick={() => setShowAdd(true)}
          className="flex items-center gap-2 px-4 py-2 bg-emerald-500 text-black rounded-xl text-sm font-bold hover:bg-emerald-400 transition-all cursor-pointer"
        >
          <UserPlus className="w-4 h-4" /> Thêm nhân viên
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {users.map(user => (
          <div key={user.id} className="bg-white/5 border border-white/10 rounded-2xl p-6 space-y-4 hover:border-emerald-500/30 transition-all">
            <div className="flex justify-between items-start">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-500 font-bold text-xl">
                  {user.name.charAt(0)}
                </div>
                <div>
                  <h4 className="font-bold text-white">{user.name}</h4>
                  <p className="text-xs text-gray-500">@{user.username}</p>
                </div>
              </div>
              <div className={cn(
                "px-2 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wider",
                user.role === 'admin' ? "bg-rose-500/20 text-rose-500" : "bg-blue-500/20 text-blue-500"
              )}>
                {user.role}
              </div>
            </div>

            <div className="flex items-center gap-2 text-xs text-gray-400">
              <Key className="w-3 h-3" /> Mật khẩu: <span className="font-mono text-white">{user.password}</span>
            </div>

            {user.role !== 'admin' && (
              <button 
                onClick={() => onDeleteUser(user.id)}
                className="w-full py-2 bg-rose-500/10 hover:bg-rose-500/20 text-rose-500 rounded-xl text-sm font-medium transition-all cursor-pointer flex items-center justify-center gap-2"
              >
                <Trash2 className="w-4 h-4" /> Xóa tài khoản
              </button>
            )}
          </div>
        ))}
      </div>

      {showAdd && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-[#1a1b1e] w-full max-w-md rounded-3xl p-8 border border-white/10 shadow-2xl space-y-6">
            <h3 className="text-xl font-bold text-white">Thêm nhân viên mới</h3>
            <div className="space-y-4">
              <div>
                <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Tên nhân viên</label>
                <input 
                  type="text" 
                  className="w-full bg-white/5 border border-white/10 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-emerald-500/50"
                  value={newUser.name}
                  onChange={(e) => setNewUser({...newUser, name: e.target.value})}
                />
              </div>
              <div>
                <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Tên đăng nhập</label>
                <input 
                  type="text" 
                  className="w-full bg-white/5 border border-white/10 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-emerald-500/50"
                  value={newUser.username}
                  onChange={(e) => setNewUser({...newUser, username: e.target.value})}
                />
              </div>
              <div>
                <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Mật khẩu</label>
                <input 
                  type="password" 
                  className="w-full bg-white/5 border border-white/10 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-emerald-500/50"
                  value={newUser.password}
                  onChange={(e) => setNewUser({...newUser, password: e.target.value})}
                />
              </div>
              <div>
                <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Vai trò</label>
                <select 
                  className="w-full bg-[#1a1b1e] border border-white/10 rounded-xl py-3 px-4 text-white focus:outline-none focus:border-emerald-500/50"
                  value={newUser.role}
                  onChange={(e) => setNewUser({...newUser, role: e.target.value as UserRole})}
                >
                  <option value="staff" className="bg-[#1a1b1e]">Nhân viên (Mặc định)</option>
                  <option value="order" className="bg-[#1a1b1e]">Nhân viên Order</option>
                  <option value="cashier" className="bg-[#1a1b1e]">Thu ngân</option>
                  <option value="kitchen" className="bg-[#1a1b1e]">Bếp</option>
                  <option value="admin" className="bg-[#1a1b1e]">Quản trị viên</option>
                </select>
              </div>
            </div>
            <div className="flex gap-3 pt-4">
              <button 
                onClick={() => setShowAdd(false)}
                className="flex-1 py-3 rounded-xl border border-white/10 text-gray-400 font-bold hover:bg-white/5 cursor-pointer"
              >
                Hủy
              </button>
              <button 
                onClick={handleAdd}
                className="flex-1 py-3 rounded-xl bg-emerald-500 text-black font-bold hover:bg-emerald-400 cursor-pointer"
              >
                Xác nhận
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
